# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import calculator_pb2 as calculator__pb2


class CalculatorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Addition = channel.unary_unary(
        '/Calculator/Addition',
        request_serializer=calculator__pb2.AdditionRequest.SerializeToString,
        response_deserializer=calculator__pb2.AdditionReply.FromString,
        )
    self.Subtraction = channel.unary_unary(
        '/Calculator/Subtraction',
        request_serializer=calculator__pb2.SubtractionRequest.SerializeToString,
        response_deserializer=calculator__pb2.SubtractionReply.FromString,
        )
    self.Multiplication = channel.unary_unary(
        '/Calculator/Multiplication',
        request_serializer=calculator__pb2.MultiplicationRequest.SerializeToString,
        response_deserializer=calculator__pb2.MultiplicationReply.FromString,
        )
    self.Division = channel.unary_unary(
        '/Calculator/Division',
        request_serializer=calculator__pb2.DivisionRequest.SerializeToString,
        response_deserializer=calculator__pb2.DivisionReply.FromString,
        )


class CalculatorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Addition(self, request, context):
    """Adds one to a number
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Subtraction(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Multiplication(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Division(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CalculatorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Addition': grpc.unary_unary_rpc_method_handler(
          servicer.Addition,
          request_deserializer=calculator__pb2.AdditionRequest.FromString,
          response_serializer=calculator__pb2.AdditionReply.SerializeToString,
      ),
      'Subtraction': grpc.unary_unary_rpc_method_handler(
          servicer.Subtraction,
          request_deserializer=calculator__pb2.SubtractionRequest.FromString,
          response_serializer=calculator__pb2.SubtractionReply.SerializeToString,
      ),
      'Multiplication': grpc.unary_unary_rpc_method_handler(
          servicer.Multiplication,
          request_deserializer=calculator__pb2.MultiplicationRequest.FromString,
          response_serializer=calculator__pb2.MultiplicationReply.SerializeToString,
      ),
      'Division': grpc.unary_unary_rpc_method_handler(
          servicer.Division,
          request_deserializer=calculator__pb2.DivisionRequest.FromString,
          response_serializer=calculator__pb2.DivisionReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Calculator', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
