# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sorter.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sorter.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0csorter.proto\"\x16\n\x04List\x12\x0e\n\x06values\x18\x01 \x03(\x02\x32\"\n\x06Sorter\x12\x18\n\x06sortit\x12\x05.List\x1a\x05.List\"\x00\x62\x06proto3')
)




_LIST = _descriptor.Descriptor(
  name='List',
  full_name='List',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='List.values', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=38,
)

DESCRIPTOR.message_types_by_name['List'] = _LIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

List = _reflection.GeneratedProtocolMessageType('List', (_message.Message,), dict(
  DESCRIPTOR = _LIST,
  __module__ = 'sorter_pb2'
  # @@protoc_insertion_point(class_scope:List)
  ))
_sym_db.RegisterMessage(List)



_SORTER = _descriptor.ServiceDescriptor(
  name='Sorter',
  full_name='Sorter',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=40,
  serialized_end=74,
  methods=[
  _descriptor.MethodDescriptor(
    name='sortit',
    full_name='Sorter.sortit',
    index=0,
    containing_service=None,
    input_type=_LIST,
    output_type=_LIST,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SORTER)

DESCRIPTOR.services_by_name['Sorter'] = _SORTER

# @@protoc_insertion_point(module_scope)
