# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='calculator.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x10\x63\x61lculator.proto\"?\n\x0f\x41\x64\x64itionRequest\x12\x15\n\rfstOperandAdd\x18\x01 \x01(\x02\x12\x15\n\rscdOperandAdd\x18\x02 \x01(\x02\"\"\n\rAdditionReply\x12\x11\n\tresultAdd\x18\x01 \x01(\x02\"B\n\x12SubtractionRequest\x12\x15\n\rfstOperandSub\x18\x01 \x01(\x02\x12\x15\n\rscdOperandSub\x18\x02 \x01(\x02\"%\n\x10SubtractionReply\x12\x11\n\tresultSub\x18\x01 \x01(\x02\"E\n\x15MultiplicationRequest\x12\x15\n\rfstOperandMul\x18\x01 \x01(\x02\x12\x15\n\rscdOperandMul\x18\x02 \x01(\x02\"(\n\x13MultiplicationReply\x12\x11\n\tresultMul\x18\x01 \x01(\x02\"?\n\x0f\x44ivisionRequest\x12\x15\n\rfstOperandDiv\x18\x01 \x01(\x02\x12\x15\n\rscdOperandDiv\x18\x02 \x01(\x02\"\"\n\rDivisionReply\x12\x11\n\tresultDiv\x18\x01 \x01(\x02\x32\xe7\x01\n\nCalculator\x12.\n\x08\x41\x64\x64ition\x12\x10.AdditionRequest\x1a\x0e.AdditionReply\"\x00\x12\x37\n\x0bSubtraction\x12\x13.SubtractionRequest\x1a\x11.SubtractionReply\"\x00\x12@\n\x0eMultiplication\x12\x16.MultiplicationRequest\x1a\x14.MultiplicationReply\"\x00\x12.\n\x08\x44ivision\x12\x10.DivisionRequest\x1a\x0e.DivisionReply\"\x00\x62\x06proto3')
)




_ADDITIONREQUEST = _descriptor.Descriptor(
  name='AdditionRequest',
  full_name='AdditionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fstOperandAdd', full_name='AdditionRequest.fstOperandAdd', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scdOperandAdd', full_name='AdditionRequest.scdOperandAdd', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=83,
)


_ADDITIONREPLY = _descriptor.Descriptor(
  name='AdditionReply',
  full_name='AdditionReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='resultAdd', full_name='AdditionReply.resultAdd', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=119,
)


_SUBTRACTIONREQUEST = _descriptor.Descriptor(
  name='SubtractionRequest',
  full_name='SubtractionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fstOperandSub', full_name='SubtractionRequest.fstOperandSub', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scdOperandSub', full_name='SubtractionRequest.scdOperandSub', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=187,
)


_SUBTRACTIONREPLY = _descriptor.Descriptor(
  name='SubtractionReply',
  full_name='SubtractionReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='resultSub', full_name='SubtractionReply.resultSub', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=189,
  serialized_end=226,
)


_MULTIPLICATIONREQUEST = _descriptor.Descriptor(
  name='MultiplicationRequest',
  full_name='MultiplicationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fstOperandMul', full_name='MultiplicationRequest.fstOperandMul', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scdOperandMul', full_name='MultiplicationRequest.scdOperandMul', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=228,
  serialized_end=297,
)


_MULTIPLICATIONREPLY = _descriptor.Descriptor(
  name='MultiplicationReply',
  full_name='MultiplicationReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='resultMul', full_name='MultiplicationReply.resultMul', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=299,
  serialized_end=339,
)


_DIVISIONREQUEST = _descriptor.Descriptor(
  name='DivisionRequest',
  full_name='DivisionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fstOperandDiv', full_name='DivisionRequest.fstOperandDiv', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scdOperandDiv', full_name='DivisionRequest.scdOperandDiv', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=341,
  serialized_end=404,
)


_DIVISIONREPLY = _descriptor.Descriptor(
  name='DivisionReply',
  full_name='DivisionReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='resultDiv', full_name='DivisionReply.resultDiv', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=406,
  serialized_end=440,
)

DESCRIPTOR.message_types_by_name['AdditionRequest'] = _ADDITIONREQUEST
DESCRIPTOR.message_types_by_name['AdditionReply'] = _ADDITIONREPLY
DESCRIPTOR.message_types_by_name['SubtractionRequest'] = _SUBTRACTIONREQUEST
DESCRIPTOR.message_types_by_name['SubtractionReply'] = _SUBTRACTIONREPLY
DESCRIPTOR.message_types_by_name['MultiplicationRequest'] = _MULTIPLICATIONREQUEST
DESCRIPTOR.message_types_by_name['MultiplicationReply'] = _MULTIPLICATIONREPLY
DESCRIPTOR.message_types_by_name['DivisionRequest'] = _DIVISIONREQUEST
DESCRIPTOR.message_types_by_name['DivisionReply'] = _DIVISIONREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AdditionRequest = _reflection.GeneratedProtocolMessageType('AdditionRequest', (_message.Message,), dict(
  DESCRIPTOR = _ADDITIONREQUEST,
  __module__ = 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:AdditionRequest)
  ))
_sym_db.RegisterMessage(AdditionRequest)

AdditionReply = _reflection.GeneratedProtocolMessageType('AdditionReply', (_message.Message,), dict(
  DESCRIPTOR = _ADDITIONREPLY,
  __module__ = 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:AdditionReply)
  ))
_sym_db.RegisterMessage(AdditionReply)

SubtractionRequest = _reflection.GeneratedProtocolMessageType('SubtractionRequest', (_message.Message,), dict(
  DESCRIPTOR = _SUBTRACTIONREQUEST,
  __module__ = 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:SubtractionRequest)
  ))
_sym_db.RegisterMessage(SubtractionRequest)

SubtractionReply = _reflection.GeneratedProtocolMessageType('SubtractionReply', (_message.Message,), dict(
  DESCRIPTOR = _SUBTRACTIONREPLY,
  __module__ = 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:SubtractionReply)
  ))
_sym_db.RegisterMessage(SubtractionReply)

MultiplicationRequest = _reflection.GeneratedProtocolMessageType('MultiplicationRequest', (_message.Message,), dict(
  DESCRIPTOR = _MULTIPLICATIONREQUEST,
  __module__ = 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:MultiplicationRequest)
  ))
_sym_db.RegisterMessage(MultiplicationRequest)

MultiplicationReply = _reflection.GeneratedProtocolMessageType('MultiplicationReply', (_message.Message,), dict(
  DESCRIPTOR = _MULTIPLICATIONREPLY,
  __module__ = 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:MultiplicationReply)
  ))
_sym_db.RegisterMessage(MultiplicationReply)

DivisionRequest = _reflection.GeneratedProtocolMessageType('DivisionRequest', (_message.Message,), dict(
  DESCRIPTOR = _DIVISIONREQUEST,
  __module__ = 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:DivisionRequest)
  ))
_sym_db.RegisterMessage(DivisionRequest)

DivisionReply = _reflection.GeneratedProtocolMessageType('DivisionReply', (_message.Message,), dict(
  DESCRIPTOR = _DIVISIONREPLY,
  __module__ = 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:DivisionReply)
  ))
_sym_db.RegisterMessage(DivisionReply)



_CALCULATOR = _descriptor.ServiceDescriptor(
  name='Calculator',
  full_name='Calculator',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=443,
  serialized_end=674,
  methods=[
  _descriptor.MethodDescriptor(
    name='Addition',
    full_name='Calculator.Addition',
    index=0,
    containing_service=None,
    input_type=_ADDITIONREQUEST,
    output_type=_ADDITIONREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Subtraction',
    full_name='Calculator.Subtraction',
    index=1,
    containing_service=None,
    input_type=_SUBTRACTIONREQUEST,
    output_type=_SUBTRACTIONREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Multiplication',
    full_name='Calculator.Multiplication',
    index=2,
    containing_service=None,
    input_type=_MULTIPLICATIONREQUEST,
    output_type=_MULTIPLICATIONREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Division',
    full_name='Calculator.Division',
    index=3,
    containing_service=None,
    input_type=_DIVISIONREQUEST,
    output_type=_DIVISIONREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CALCULATOR)

DESCRIPTOR.services_by_name['Calculator'] = _CALCULATOR

# @@protoc_insertion_point(module_scope)
