# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: average.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='average.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\raverage.proto\"\x16\n\x04List\x12\x0e\n\x06values\x18\x01 \x03(\x03\"\x12\n\x03\x61vg\x12\x0b\n\x03num\x18\x01 \x01(\x03\x32\"\n\x08\x41verager\x12\x16\n\x05\x61vgit\x12\x05.List\x1a\x04.avg\"\x00\x62\x06proto3')
)




_LIST = _descriptor.Descriptor(
  name='List',
  full_name='List',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='List.values', index=0,
      number=1, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=39,
)


_AVG = _descriptor.Descriptor(
  name='avg',
  full_name='avg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num', full_name='avg.num', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=59,
)

DESCRIPTOR.message_types_by_name['List'] = _LIST
DESCRIPTOR.message_types_by_name['avg'] = _AVG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

List = _reflection.GeneratedProtocolMessageType('List', (_message.Message,), dict(
  DESCRIPTOR = _LIST,
  __module__ = 'average_pb2'
  # @@protoc_insertion_point(class_scope:List)
  ))
_sym_db.RegisterMessage(List)

avg = _reflection.GeneratedProtocolMessageType('avg', (_message.Message,), dict(
  DESCRIPTOR = _AVG,
  __module__ = 'average_pb2'
  # @@protoc_insertion_point(class_scope:avg)
  ))
_sym_db.RegisterMessage(avg)



_AVERAGER = _descriptor.ServiceDescriptor(
  name='Averager',
  full_name='Averager',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=61,
  serialized_end=95,
  methods=[
  _descriptor.MethodDescriptor(
    name='avgit',
    full_name='Averager.avgit',
    index=0,
    containing_service=None,
    input_type=_LIST,
    output_type=_AVG,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_AVERAGER)

DESCRIPTOR.services_by_name['Averager'] = _AVERAGER

# @@protoc_insertion_point(module_scope)
