# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import average_pb2 as average__pb2


class AveragerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.avgit = channel.unary_unary(
        '/Averager/avgit',
        request_serializer=average__pb2.List.SerializeToString,
        response_deserializer=average__pb2.avg.FromString,
        )


class AveragerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def avgit(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AveragerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'avgit': grpc.unary_unary_rpc_method_handler(
          servicer.avgit,
          request_deserializer=average__pb2.List.FromString,
          response_serializer=average__pb2.avg.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Averager', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
