# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stringFormatter.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='stringFormatter.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x15stringFormatter.proto\"#\n\x0cUpperRequest\x12\x13\n\x0bupperReqStr\x18\x01 \x01(\t\"!\n\nUpperReply\x12\x13\n\x0bupperRepStr\x18\x01 \x01(\t\"#\n\x0cLowerRequest\x12\x13\n\x0blowerReqStr\x18\x01 \x01(\t\"!\n\nLowerReply\x12\x13\n\x0blowerRepStr\x18\x01 \x01(\t\"#\n\rProperRequest\x12\x12\n\npropReqStr\x18\x01 \x01(\t\"!\n\x0bProperReply\x12\x12\n\npropRepStr\x18\x01 \x01(\t2\x83\x01\n\x0fStringFormatter\x12#\n\x05Upper\x12\r.UpperRequest\x1a\x0b.UpperReply\x12#\n\x05Lower\x12\r.LowerRequest\x1a\x0b.LowerReply\x12&\n\x06Proper\x12\x0e.ProperRequest\x1a\x0c.ProperReplyb\x06proto3')
)




_UPPERREQUEST = _descriptor.Descriptor(
  name='UpperRequest',
  full_name='UpperRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='upperReqStr', full_name='UpperRequest.upperReqStr', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=60,
)


_UPPERREPLY = _descriptor.Descriptor(
  name='UpperReply',
  full_name='UpperReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='upperRepStr', full_name='UpperReply.upperRepStr', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=95,
)


_LOWERREQUEST = _descriptor.Descriptor(
  name='LowerRequest',
  full_name='LowerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lowerReqStr', full_name='LowerRequest.lowerReqStr', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=132,
)


_LOWERREPLY = _descriptor.Descriptor(
  name='LowerReply',
  full_name='LowerReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lowerRepStr', full_name='LowerReply.lowerRepStr', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=167,
)


_PROPERREQUEST = _descriptor.Descriptor(
  name='ProperRequest',
  full_name='ProperRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='propReqStr', full_name='ProperRequest.propReqStr', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=204,
)


_PROPERREPLY = _descriptor.Descriptor(
  name='ProperReply',
  full_name='ProperReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='propRepStr', full_name='ProperReply.propRepStr', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=206,
  serialized_end=239,
)

DESCRIPTOR.message_types_by_name['UpperRequest'] = _UPPERREQUEST
DESCRIPTOR.message_types_by_name['UpperReply'] = _UPPERREPLY
DESCRIPTOR.message_types_by_name['LowerRequest'] = _LOWERREQUEST
DESCRIPTOR.message_types_by_name['LowerReply'] = _LOWERREPLY
DESCRIPTOR.message_types_by_name['ProperRequest'] = _PROPERREQUEST
DESCRIPTOR.message_types_by_name['ProperReply'] = _PROPERREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UpperRequest = _reflection.GeneratedProtocolMessageType('UpperRequest', (_message.Message,), dict(
  DESCRIPTOR = _UPPERREQUEST,
  __module__ = 'stringFormatter_pb2'
  # @@protoc_insertion_point(class_scope:UpperRequest)
  ))
_sym_db.RegisterMessage(UpperRequest)

UpperReply = _reflection.GeneratedProtocolMessageType('UpperReply', (_message.Message,), dict(
  DESCRIPTOR = _UPPERREPLY,
  __module__ = 'stringFormatter_pb2'
  # @@protoc_insertion_point(class_scope:UpperReply)
  ))
_sym_db.RegisterMessage(UpperReply)

LowerRequest = _reflection.GeneratedProtocolMessageType('LowerRequest', (_message.Message,), dict(
  DESCRIPTOR = _LOWERREQUEST,
  __module__ = 'stringFormatter_pb2'
  # @@protoc_insertion_point(class_scope:LowerRequest)
  ))
_sym_db.RegisterMessage(LowerRequest)

LowerReply = _reflection.GeneratedProtocolMessageType('LowerReply', (_message.Message,), dict(
  DESCRIPTOR = _LOWERREPLY,
  __module__ = 'stringFormatter_pb2'
  # @@protoc_insertion_point(class_scope:LowerReply)
  ))
_sym_db.RegisterMessage(LowerReply)

ProperRequest = _reflection.GeneratedProtocolMessageType('ProperRequest', (_message.Message,), dict(
  DESCRIPTOR = _PROPERREQUEST,
  __module__ = 'stringFormatter_pb2'
  # @@protoc_insertion_point(class_scope:ProperRequest)
  ))
_sym_db.RegisterMessage(ProperRequest)

ProperReply = _reflection.GeneratedProtocolMessageType('ProperReply', (_message.Message,), dict(
  DESCRIPTOR = _PROPERREPLY,
  __module__ = 'stringFormatter_pb2'
  # @@protoc_insertion_point(class_scope:ProperReply)
  ))
_sym_db.RegisterMessage(ProperReply)



_STRINGFORMATTER = _descriptor.ServiceDescriptor(
  name='StringFormatter',
  full_name='StringFormatter',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=242,
  serialized_end=373,
  methods=[
  _descriptor.MethodDescriptor(
    name='Upper',
    full_name='StringFormatter.Upper',
    index=0,
    containing_service=None,
    input_type=_UPPERREQUEST,
    output_type=_UPPERREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Lower',
    full_name='StringFormatter.Lower',
    index=1,
    containing_service=None,
    input_type=_LOWERREQUEST,
    output_type=_LOWERREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Proper',
    full_name='StringFormatter.Proper',
    index=2,
    containing_service=None,
    input_type=_PROPERREQUEST,
    output_type=_PROPERREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_STRINGFORMATTER)

DESCRIPTOR.services_by_name['StringFormatter'] = _STRINGFORMATTER

# @@protoc_insertion_point(module_scope)
