# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import void_pb2 as void__pb2


class DoerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.DoSomething = channel.unary_unary(
        '/Doer/DoSomething',
        request_serializer=void__pb2.Empty.SerializeToString,
        response_deserializer=void__pb2.Empty.FromString,
        )


class DoerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def DoSomething(self, request, context):
    """Does nothing
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DoerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'DoSomething': grpc.unary_unary_rpc_method_handler(
          servicer.DoSomething,
          request_deserializer=void__pb2.Empty.FromString,
          response_serializer=void__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Doer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
