# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: void.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='void.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\nvoid.proto\"\x07\n\x05\x45mpty2%\n\x04\x44oer\x12\x1d\n\x0b\x44oSomething\x12\x06.Empty\x1a\x06.Emptyb\x06proto3')
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=21,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'void_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  ))
_sym_db.RegisterMessage(Empty)



_DOER = _descriptor.ServiceDescriptor(
  name='Doer',
  full_name='Doer',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=23,
  serialized_end=60,
  methods=[
  _descriptor.MethodDescriptor(
    name='DoSomething',
    full_name='Doer.DoSomething',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_EMPTY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DOER)

DESCRIPTOR.services_by_name['Doer'] = _DOER

# @@protoc_insertion_point(module_scope)
