# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: analyzer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='analyzer.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0e\x61nalyzer.proto\"\xc3\x01\n\x04\x44\x61ta\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x1a\n\x05level\x18\x03 \x01(\x0b\x32\x0b.Data.Level\x12\x19\n\x05plays\x18\x04 \x03(\x0b\x32\n.Data.Play\x1a:\n\x04Play\x12\x0c\n\x04time\x18\x01 \x01(\x02\x12\x11\n\tprecision\x18\x02 \x01(\x02\x12\x11\n\ttimestamp\x18\x03 \x01(\x05\x1a*\n\x05Level\x12\r\n\x05\x62onus\x18\x01 \x01(\x05\x12\x12\n\nmultiplier\x18\x02 \x01(\x02\"\x16\n\x05Score\x12\r\n\x05score\x18\x01 \x01(\x05\x32$\n\x08\x41nalyzer\x12\x18\n\x05score\x12\x05.Data\x1a\x06.Score\"\x00\x62\x06proto3')
)




_DATA_PLAY = _descriptor.Descriptor(
  name='Play',
  full_name='Data.Play',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='Data.Play.time', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='precision', full_name='Data.Play.precision', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='Data.Play.timestamp', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=170,
)

_DATA_LEVEL = _descriptor.Descriptor(
  name='Level',
  full_name='Data.Level',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bonus', full_name='Data.Level.bonus', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='multiplier', full_name='Data.Level.multiplier', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=214,
)

_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Data.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='username', full_name='Data.username', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='level', full_name='Data.level', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='plays', full_name='Data.plays', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DATA_PLAY, _DATA_LEVEL, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=214,
)


_SCORE = _descriptor.Descriptor(
  name='Score',
  full_name='Score',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='score', full_name='Score.score', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=238,
)

_DATA_PLAY.containing_type = _DATA
_DATA_LEVEL.containing_type = _DATA
_DATA.fields_by_name['level'].message_type = _DATA_LEVEL
_DATA.fields_by_name['plays'].message_type = _DATA_PLAY
DESCRIPTOR.message_types_by_name['Data'] = _DATA
DESCRIPTOR.message_types_by_name['Score'] = _SCORE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), dict(

  Play = _reflection.GeneratedProtocolMessageType('Play', (_message.Message,), dict(
    DESCRIPTOR = _DATA_PLAY,
    __module__ = 'analyzer_pb2'
    # @@protoc_insertion_point(class_scope:Data.Play)
    ))
  ,

  Level = _reflection.GeneratedProtocolMessageType('Level', (_message.Message,), dict(
    DESCRIPTOR = _DATA_LEVEL,
    __module__ = 'analyzer_pb2'
    # @@protoc_insertion_point(class_scope:Data.Level)
    ))
  ,
  DESCRIPTOR = _DATA,
  __module__ = 'analyzer_pb2'
  # @@protoc_insertion_point(class_scope:Data)
  ))
_sym_db.RegisterMessage(Data)
_sym_db.RegisterMessage(Data.Play)
_sym_db.RegisterMessage(Data.Level)

Score = _reflection.GeneratedProtocolMessageType('Score', (_message.Message,), dict(
  DESCRIPTOR = _SCORE,
  __module__ = 'analyzer_pb2'
  # @@protoc_insertion_point(class_scope:Score)
  ))
_sym_db.RegisterMessage(Score)



_ANALYZER = _descriptor.ServiceDescriptor(
  name='Analyzer',
  full_name='Analyzer',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=240,
  serialized_end=276,
  methods=[
  _descriptor.MethodDescriptor(
    name='score',
    full_name='Analyzer.score',
    index=0,
    containing_service=None,
    input_type=_DATA,
    output_type=_SCORE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ANALYZER)

DESCRIPTOR.services_by_name['Analyzer'] = _ANALYZER

# @@protoc_insertion_point(module_scope)
